version: '3.6'
services:
  wireguard:
    build: ./
    # image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file:
       - ${PWD}/.env
    environment:
      - PUID=1000
      - PGID=1000
      - PEERDNS=auto
      - PERSISTENTKEEPALIVE_PEERS=
      - LOG_CONFS=true
    volumes:
      - ${PWD}/config:/config
      - /lib/modules:/lib/modules
    ports:
      - ${SERVERPORT}:${SERVERPORT}/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    command: wg-api --device wg0 --listen 0.0.0.0:8182
    restart: always

#   wg-json-api:
#     image: james/wg-api:latest
#     container_name: wg-json-api
#     restart: always
#     volumes:
#       - /lib/modules:/lib/modules
#     cap_add:
#       - NET_ADMIN
#       - SYS_MODULE
#     command: wg-api --device wg0 --listen 0.0.0.0:8182
#     depends_on:
#       - wireguard

  wg-gen-web-demo:
    image: vx3r/wg-gen-web:latest
    container_name: wg-gen-web-demo
    restart: always
    ports:
      - ${ADMIN_WEB_PORT}:8080
    env_file:
       - ${PWD}/.env
    environment:
      - WG_STATS_API=http://wireguard:8182
      - WG_CONF_DIR=/data
      - WG_INTERFACE_NAME=wg0.conf
    volumes:
      - ${PWD}/config:/data
    depends_on:
      - wireguard
